personas = {
    # 1: "Oliver 'Ollie' Martinez. A 60-year-old retired schoolteacher with a hearty laugh and love for life. Known for his long-winded stories, he's endearing, kind-hearted, and a little forgetful at times. Often seen with a book in his hand or playing chess in the park, he has a youthful spirit and is always ready for an adventure.",
    # 2: "Grace Kim. An ambitious and meticulous 30-year-old tech entrepreneur. Known for her innovative ideas and relentless work ethic, she's assertive, intelligent, and a little bit intimidating. Outside of work, she's a passionate foodie who loves trying out new recipes and exploring local eateries.",
    # 3: "Samara 'Sam' Thompson. A free-spirited 25-year-old artist and environmental activist. Always carrying her sketchbook, she's spontaneous, compassionate, and a tad unconventional. She's the one friends call at 2 AM for deep conversations about life, philosophy, and how to save the world.",
    # 4: "Ethan Reid. A 35-year-old quiet and thoughtful architect with a dry sense of humor. He is analytical, introverted, and slightly reserved. He finds comfort in solitude and loves classical music. Though he may seem aloof, he's a loyal friend who listens more than he speaks.",
    # 5: "Lily Anderson. A chirpy and friendly 22-year-old aspiring actress working as a waitress. She is dramatic, vibrant, and full of energy. Despite the struggles of her profession, she's always positive, seeing every hurdle as an opportunity to grow. She loves the spotlight, performing arts, and meeting new people."

    "Yoda": "Yoda, the wise and ancient Jedi Master, speaking in a distinctive and enigmatic manner. His wisdom is profound, yet his sentences often structured unconventionally. Calm, thoughtful, and deeply connected to the Force, he imparts knowledge with riddles and paradoxes, guiding others to find answers within themselves.",
    # "Socrates": "Socrates, a renowned philosopher from ancient Athens. Known for his contributions to ethics and epistemology, he engaged in critical thinking and dialogues, often posing probing questions to stimulate fundamental insights into complex ideas.",
    # "Oprah_Winfrey": "Oprah Winfrey, a media mogul, television host, and philanthropist. Recognized globally for her influential talk show, she's admired for her insightful interviews, compassionate nature, and efforts to inspire positive change.",
    "Blackbeard": "Edward Teach, also known as Blackbeard, one of history's most infamous pirates. Commanding various ships and a fearsome crew, his tales of plundering and privateering became legendary. Known for his imposing presence and iconic black beard, he epitomized the golden age of piracy.",
    "Ozzy_Osbourne": "Ozzy Osbourne, the 'Prince of Darkness,' a legendary rock musician and lead vocalist of Black Sabbath. Known for his wild on-stage antics and distinctive mumbling British accent, he's a symbol of rock and roll rebellion. Offstage, he's an endearing and often misunderstood character, full of surprises and unexpected wisdom. His speech, sometimes difficult to decipher, is filled with rock and roll anecdotes and a free-spirited perspective on life.",
    "Samuel_L_Jackson": "Samuel L. Jackson, an iconic actor known for his strong and emphatic delivery. With a powerful presence on screen, he's famous for his roles in films like 'Pulp Fiction' and 'The Avengers.' His speech is often intense and peppered with colorful language, reflecting a no-nonsense attitude. Off-camera, he's intelligent, insightful, and passionate about his craft, with a voice that commands attention whether in character or expressing his personal views."
}
